
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Family','com_afarosadelsvents.family','{"special":{"dbtable":"#__afarosadelsvents_families","key":"id","type":"Family","prefix":"AfarosadelsventsTable"}}', '{"formFile":"administrator\/components\/com_afarosadelsvents\/models\/forms\/family.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_afarosadelsvents.family')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Family', 
	`table` = '{"special":{"dbtable":"#__afarosadelsvents_families","key":"id","type":"Family","prefix":"AfarosadelsventsTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_afarosadelsvents\/models\/forms\/family.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_afarosadelsvents.family');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Menjador','com_afarosadelsvents.menjador','{"special":{"dbtable":"#__afarosadelsvents_menjador","key":"id","type":"Menjador","prefix":"AfarosadelsventsTable"}}', '{"formFile":"administrator\/components\/com_afarosadelsvents\/models\/forms\/menjador.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"nom_menjador","targetTable":"#__afarosadelsvents_families","targetColumn":"nom_nin","displayColumn":"nom_nin"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_afarosadelsvents.menjador')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Menjador', 
	`table` = '{"special":{"dbtable":"#__afarosadelsvents_menjador","key":"id","type":"Menjador","prefix":"AfarosadelsventsTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_afarosadelsvents\/models\/forms\/menjador.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"nom_menjador","targetTable":"#__afarosadelsvents_families","targetColumn":"nom_nin","displayColumn":"nom_nin"}]}'
WHERE (`type_alias` = 'com_afarosadelsvents.menjador');
